function [D,y] = parse_credit_gen(varargin)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    ./credit.data
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/05/14 12:04:26

% Parse
p = inputParser;
addOptional(p, 'save', false);
addOptional(p, 'impute', false);
parse(p, varargin{:});

%% Initialize variables.
filename = './credit.data';
delimiter = ',';

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If
% an error occurs for a different file, try regenerating the code from the
% Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,8,11,14,15]
    % Converts text in the input cell array to numbers. Replaced non-numeric text
    % with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,3,8,11,14,15]);
rawCellColumns = raw(:, [1,4,5,6,7,9,10,12,13,16]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Map to numeric dataset

numIndex = [2,3,8,11,14,15];
strIndex = [1,4,5,6,7,9,10,12,13,16];

A = NaN(size(rawCellColumns));
for a = 1:size(rawCellColumns,2)
    
   ua = unique(rawCellColumns(:,a));
   for u = 1:length(ua)
       ix = strcmp(rawCellColumns(:,a),ua{u});
       if strcmp(ua{u},'?')
            A(ix,a) = NaN;
       else
            A(ix,a) = u;
       end
   end
end

D = NaN(size(raw));
D(:,numIndex) = cell2mat(rawNumericColumns);
D(:,strIndex) = A;

y = D(:,end);
y(y==2) = -1;
D = D(:,1:end-1);

if p.Results.impute
    D(isnan(D)) = 0;
end

if p.Results.save
    save('credit', 'D','y');
end

end
